name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu Checkout Et
        uses: actions/checkout@v2

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Testleri Çalıştır
        run: npm test

      - name: Docker Build
        run: docker build -t my-app .

      - name: Docker Image'ı Docker Hub'a Push Et
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app mydockerhubuser/my-app:latest
          docker push mydockerhubuser/my-app:latest
